name: Deploy NestJS to EC2

on:
  push:
    branches: [ "main" ] # El despliegue correrá cada vez que envíes cambios a la rama main

env:
  AWS_REGION: sa-east-1                      # Configurado para São Paulo (tu servidor)
  ECR_REPOSITORY: hackaton/backend           # El nombre exacto de tu repositorio en AWS ECR
  EC2_USER: ubuntu                           # Usuario por defecto para servidores Ubuntu en AWS

jobs:
  build-and-ship:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        # Manteniendo tu corrección para resolver workspaces desde la raíz
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f backend/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ env.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: ECR_REGISTRY,ECR_REPOSITORY,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION
        script: |
          # Actualizar e instalar awscli en tu servidor si no se instaló antes
          if ! command -v aws &> /dev/null; then sudo apt-get update && sudo apt-get install awscli -y; fi
          
          # Autenticar Docker dentro de tu EC2 con AWS ECR usando las variables inyectadas de forma segura
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          
          # Detener y remover el contenedor viejo si ya existiera
          docker stop nestjs_api || true
          docker rm nestjs_api || true
          
          # Descargar la nueva versión de tu backend
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Encender el contenedor con el puerto 3000 y el CORS abierto para el Front
          docker run -d \
            --name nestjs_api \
            -p 3000:3000 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e CORS_ORIGIN="*" \
            --restart always \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest
